[package]
name = "seedcracker_cli"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
mcseedcracker = { path = "../seedcracker_lib" }
mcsci = { path = "../seedcracker_protocol" }
ratatui = "0.29.0"
clap = { version = "4.5.41", features = ["derive"] }
